# Generated by Django 5.0.6 on 2024-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='time_since_last_commit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
