# Generated by Django 5.0.6 on 2024-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
